"""Aggregator agent.

Takes the issue lists from the security, performance, and style agents,
deduplicates them, ranks by severity, computes an overall score, and produces a
final structured :class:`ReviewReport`.

Deduplication, ranking, severity counts, and the score are computed
deterministically (so the report is stable and works without an API call). The
narrative ``summary`` and ``top_recommendations`` are generated by Claude when
an API key is available, with a deterministic fallback otherwise.
"""

from __future__ import annotations

from pydantic import BaseModel, Field

from agents.base import (
    SEVERITY_ORDER,
    SEVERITY_WEIGHT,
    Issue,
    Severity,
    get_llm,
)


class ReviewReport(BaseModel):
    """Final structured report returned to API clients."""

    summary: str
    total_issues: int
    issues_by_severity: dict[str, int]
    top_recommendations: list[str] = Field(default_factory=list, max_length=5)
    overall_score: int = Field(ge=0, le=100)
    issues: list[Issue] = Field(default_factory=list)


class _Narrative(BaseModel):
    """LLM-generated narrative portion of the report."""

    summary: str
    top_recommendations: list[str] = Field(default_factory=list, max_length=5)


def _dedupe(issues: list[Issue]) -> list[Issue]:
    """Drop near-duplicate issues (same file/line and similar description)."""
    seen: set[tuple] = set()
    unique: list[Issue] = []
    for issue in issues:
        key = (
            issue.file,
            issue.line_number,
            issue.category.lower().strip(),
            issue.description.lower().strip()[:60],
        )
        if key in seen:
            continue
        seen.add(key)
        unique.append(issue)
    return unique


def _rank(issues: list[Issue]) -> list[Issue]:
    """Sort issues most-severe first, then by file/line for stability."""
    return sorted(
        issues,
        key=lambda i: (
            SEVERITY_ORDER.get(i.severity, 99),
            i.file or "",
            i.line_number if i.line_number is not None else 1 << 30,
        ),
    )


def _count_by_severity(issues: list[Issue]) -> dict[str, int]:
    counts = {s.value: 0 for s in Severity}
    for issue in issues:
        counts[issue.severity.value] = counts.get(issue.severity.value, 0) + 1
    return counts


def _score(issues: list[Issue]) -> int:
    """Score the diff from the actual findings.

    Start at 100 and subtract per issue by severity:
    25 (critical), 10 (high), 5 (medium), 2 (low). Floored at 0. With no
    issues (e.g. a docs-only PR) the score is 100.
    """
    penalty = sum(SEVERITY_WEIGHT.get(i.severity, 0) for i in issues)
    return max(0, 100 - penalty)


def _fallback_recommendations(issues: list[Issue]) -> list[str]:
    return [
        f"[{i.severity.value.upper()}] {i.category}: {i.fix_suggestion}"
        for i in issues[:5]
    ]


async def _narrative(issues: list[Issue], score: int) -> _Narrative:
    """Generate the summary + recommendations, falling back if the LLM fails."""
    if not issues:
        return _Narrative(
            summary="No issues found. The diff looks clean across security, "
            "performance, and style checks.",
            top_recommendations=[],
        )

    bullet_lines = "\n".join(
        f"- [{i.severity.value}] ({i.agent}) {i.category}: {i.description}"
        for i in issues[:30]
    )
    try:
        llm = get_llm().with_structured_output(_Narrative)
        result: _Narrative = await llm.ainvoke(
            [
                (
                    "system",
                    "You are the lead reviewer summarizing a code review. Write a "
                    "concise 2-4 sentence summary of the overall health of the diff "
                    "and the most important themes. Then give up to 5 prioritized, "
                    "actionable recommendations (most impactful first).",
                ),
                (
                    "human",
                    f"Overall score: {score}/100. Findings:\n{bullet_lines}",
                ),
            ]
        )
        # Enforce the max of 5 recommendations defensively.
        result.top_recommendations = result.top_recommendations[:5]
        return result
    except Exception:
        crit = sum(1 for i in issues if i.severity == Severity.CRITICAL)
        high = sum(1 for i in issues if i.severity == Severity.HIGH)
        return _Narrative(
            summary=(
                f"Found {len(issues)} issue(s) (score {score}/100): "
                f"{crit} critical, {high} high. Review the highest-severity "
                "findings before merging."
            ),
            top_recommendations=_fallback_recommendations(issues),
        )


async def aggregate(
    security_issues: list[Issue],
    performance_issues: list[Issue],
    style_issues: list[Issue],
) -> ReviewReport:
    """Combine all agent outputs into a single ranked :class:`ReviewReport`."""
    all_issues = _rank(_dedupe([*security_issues, *performance_issues, *style_issues]))
    score = _score(all_issues)
    narrative = await _narrative(all_issues, score)

    return ReviewReport(
        summary=narrative.summary,
        total_issues=len(all_issues),
        issues_by_severity=_count_by_severity(all_issues),
        top_recommendations=narrative.top_recommendations,
        overall_score=score,
        issues=all_issues,
    )
